### PR TITLE
Add getters for related entities

### PR DESCRIPTION
**Pull request by XenosEleatikos**

### CODE REVIEW

**Comment by roland-d** [comment]
@XenosEleatikos I have been trying to test this with this filter:
```php
$artistFilter->addArtistNameWithAccents(new Name('Jason Mraz'));
```
but I am getting the following error:
```
PHP Warning:  Undefined array key "release" in xenos/vendor/xenos/musicbrainz/src/Helper/RelationFactory.php on line 48
```

Not related to this PR but I also got an error relating to this Artist Series missing:
https://musicbrainz.org/relationship/d1a845d1-8c03-3191-9454-e4e8d37fa5e0

From code review the PR looks fine but I cannot fully test it due to the above issues.

**Comment by XenosEleatikos** [comment]
I tested with

```
        $artistFilter = new ArtistFilter();
        $artistFilter->addArtistNameWithAccents(new Name('Jason Mraz'));
        $artist = $mb->api()->search()->artist(
            $artistFilter,
            new PageFilter()
        );
```
and it worked. Can you please provide your exact code for reproducing this error?

**Comment by roland-d** [comment]
@XenosEleatikos Sure, here is the full code I used to test:
```php
<?php

require "vendor/autoload.php";

use MusicBrainz\Filter\PageFilter;
use MusicBrainz\Filter\Search\ArtistFilter;
use MusicBrainz\MusicBrainz;
use MusicBrainz\HttpAdapter\GuzzleHttpAdapter;
use GuzzleHttp\Client;
use MusicBrainz\Supplement\Lookup\ArtistFields;
use MusicBrainz\Value\Artist;
use MusicBrainz\Value\MBID;
use MusicBrainz\Value\Name;

$guzzleHttpAdapter = new GuzzleHttpAdapter(new Client);
$musicBrainz       = new MusicBrainz($guzzleHttpAdapter);
$artistFilter = new ArtistFilter;
$artistFilter->addArtistNameWithAccents(new Name('Jason Mraz'));
$pageFilter = new PageFilter(0, 1);

$artistList = $musicBrainz->api()->search()->artist($artistFilter, $pageFilter);
/** @var Artist $current */
$current = $artistList->current()->getArtist();

$fields = (new ArtistFields)
    ->includeAreaRelations()
    ->includeArtistRelations()
    ->includeEventRelations()
    ->includeInstrumentRelations()
    ->includeLabelRelations()
    ->includePlaceRelations()
    ->includeRecordingRelations()
    ->includeReleaseRelations()
    ->includeReleaseGroupRelations()
    ->includeSeriesRelations()
    ->includeWorkRelations();

$artist = $musicBrainz->api()->lookup()->artist(
    new MBID($current->getMBID()),
    $fields
);

foreach ($artist->getRelations()->getAreaRelations() as $relation) {
    print_r($relation->getArea());
}

foreach ($artist->getRelations()->getArtistRelations() as $relation) {
    print_r($relation->getArtist());
}

foreach ($artist->getRelations()->getEventRelations() as $relation) {
    print_r($relation->getEvent());
}

foreach ($artist->getRelations()->getInstrumentRelations() as $relation) {
    print_r($relation->getInstrument());
}

foreach ($artist->getRelations()->getLabelRelations() as $relation) {
    print_r($relation->getLabel());
}

foreach ($artist->getRelations()->getPlaceRelations() as $relation) {
    print_r($relation->getPlace());
}

foreach ($artist->getRelations()->getRecordingRelations() as $relation) {
    print_r($relation->getRecording());
}

foreach ($artist->getRelations()->getReleaseRelations() as $relation) {
    print_r($relation->getRelease());
}

foreach ($artist->getRelations()->getReleaseGroupRelations() as $relation) {
    print_r($relation->getReleaseGroup());
}

foreach ($artist->getRelations()->getSeriesRelations() as $relation) {
    print_r($relation->getSeries());
}

foreach ($artist->getRelations()->getWorkRelations() as $relation) {
    print_r($relation->getWork());
}
```

**Comment by XenosEleatikos** [comment]
Hi Roland,
for now I implemented an error handling nor unknown relation types. I haven't used this library since years, so maybe in the meanwhile MusicBrainz implemented new relation types. (Or I just forgot to implement some.)

The library should now ignore unknown relations and log an error. I will implement https://musicbrainz.org/relationship/d1a845d1-8c03-3191-9454-e4e8d37fa5e0 when I find some free time. Feel free to drop me a message, if you find more relations that are not yet implemented in the library.

**Comment by roland-d** [comment]
Hello,

I have sent a PR for the `PartOf` relation. This PR is working fine for me. I am going to raise another issue that I ran into but is not specifically related to this.

**Pull request merged**
